var text = [
	"radioactive contamination is eliminated", 
	"stopped the collapse of red blood cells",
	"restored vascular tissue",
	"regeneration of the skin was performed",
	"muscle building is performed",
	"corrected the defect of the retina",
	"maxillary sinuses are pneumatized",
	"the intestinal microflora is inhabited by beneficial microorganisms",
	"pathological growth of epidermal cells was stopped",
	"the hormonal background is aligned with the nominal value",
	"the immune system is supplemented with effective antibodies",
	"balanced composition of spinal fluid",
	"conducted gidratatsiya whole body", 
	"the formation of glucose by the liver from non-carbohydrate compounds was restored",
	"the body is provided with totipotent cells",
	"the negative impact of physical and chemical nature has been eliminated",
	"restored electrolyte balance of blood",
	"the catalytic action of enzymes complemented by coenzymes",
	"withdrawn from the body of toxic substances and their metabolites",
	"restored water-electrolyte homeostasis",
	"the fluctuation of cerebrospinal fluid is restored to optimal parameters",
	"constant intracranial pressure has been maintained",
	"fixed diffuse changes in lung tissue",  
	"pancreatic tissue is fully regenerated",
	"saturation of the body with vitamins and minerals restored",
	"the cells were saturated with oxygen",
	"damage to neural connections of the brain was restored",
	"blood pressure is regulated",
	"increased resistance of the body to various adverse effects",
	"the ability of cells to repair DNA damage has been restored",
	"tachycardia and tremor eliminated",
	"vegetososudistaya symptoms completely eliminated"
	];